### ISSUE TITLE
Is this the actual WormGPT form GPT-J? Like it doesn't use openai api key?

### ISSUE THREAD

**Issue by Goofy-Uses-Game-Bots** [Catdevzsh/WormGPT3#1]

**Comment by Catdevzsh** [comment]
Just use ollama or local ai or shuttle

**Comment by Catdevzsh** [comment]
change the base url to gpt-j idk lol

**Comment by Catdevzsh** [comment]
## OPENAI_API_BASE_URL - Custom url for the OpenAI API, useful for connecting to custom backends. No effect if USE_AZURE is true, leave blank to keep the default url
# the following is an example:
OPENAI_API_BASE_URL=https://api.shuttleai.app/v1
 set it to this and by a shuttle gpt3 same as gptj but better more models uncensored

**Comment by Goofy-Uses-Game-Bots** [comment]
> Just use ollama or local ai or shuttle 

How?
